from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
RESULTS_DIR = PROJECT_ROOT / "results"

RUN_LABEL = "BeH2_single_point_he"

RUN_SINGLE_POINT = False
RUN_REPS_EXPERIMENT = False
RUN_OPTIMIZER_EXPERIMENT = True
RUN_BOND_SCAN = False
RUN_BASIS_COMPARISON = False
RUN_ANSATZ_MODE_COMPARISON = False
RUN_REPEATED_SINGLE_POINT = False
RUN_REPEATED_OPTIMIZER_EXPERIMENT = False
RUN_REPEATED_ANSATZ_MODE_EXPERIMENT = False
RUN_OPTIMIZER_REPS_GRID = False

BASIS = "sto3g"
BASIS_SETS_TO_COMPARE = ["sto3g", "3-21g"]

DEFAULT_ANSATZ_MODE = "hardware_efficient"
ANSATZ_MODES_TO_COMPARE = ["hardware_efficient", "uccsd_hf"]

DEFAULT_BOND_LENGTH = 1.6
BOND_LENGTHS = [1.0, 1.5, 2.0, 2.5, 3.0]

DEFAULT_REPS = 2
REPS_EXPERIMENT = [1, 5, 10, 15]

OPTIMIZER_NAME = "COBYLA"
COBYLA_MAXITER = 4000
SPSA_MAXITER = 0.5 * COBYLA_MAXITER
GD_MAXITER = COBYLA_MAXITER / 25
GD_LEARNING_RATE = 0.2
OPTIMIZERS_TO_COMPARE = ["COBYLA", "SPSA", "GRADIENT_DESCENT"]

RANDOM_SEED = None
NUM_TRIALS = 5

MOLECULE_NAME = "BeH2"  # "LiH" or "BeH2"
CHARGE = 0
SPIN = 0

MAPPER_NAME = "jordan_wigner"
ENTANGLEMENT_PATTERN = "linear"
MAX_EXACT_QUBITS = 16
USE_TQDM = True
ANSATZ_FOLD = 50
FIG_DPI = 300
PREVIEW_TERM_COUNT = 15

SAVE_HAMILTONIAN_PREVIEW = True
SAVE_CONVERGENCE_PLOT = True
SAVE_REPS_OVERLAY_PLOT = True
SAVE_BOND_SCAN_PLOT = True
SAVE_ANSATZ_FIGURE = True
SAVE_BOND_ERROR_PLOT = True
SAVE_REPS_ERROR_PLOT = True
SAVE_OPTIMIZER_OVERLAY_PLOT = True
SAVE_BASIS_ERROR_PLOT = True
SAVE_ANSATZ_MODE_ERROR_PLOT = True
SAVE_REPEATED_TRIALS_PLOT = True
SAVE_REPEATED_TRIALS_SUMMARY = True




def ensure_results_dir() -> Path:
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    return RESULTS_DIR